### ISSUE TITLE
error = different account recovered

### ISSUE THREAD

**Issue by enzofoucaud** [multiversx/mx-sdk-go#127]
Hi !

I try to access my account with the LoadPrivateKeyFromJsonFile function but I have this following error :
`ERROR[2023-03-08 10:31:34.539]   error loading wallet                     error = different account recovered`

```go
file, err := w.LoadPrivateKeyFromJsonFile("wallet.json", "password")
if err != nil {
   log.Error("error loading wallet", "error", err)
   panic(err)
}```

**Comment by bogdan-rosianu** [comment]
Hi. Thanks for opening this issue. We were able to reproduce and we'll come with a fix ASAP.

**Comment by bogdan-rosianu** [comment]
#128 fixes this issues

**Comment by bogdan-rosianu** [comment]
Please use the current latest tag, `v1.2.6`. Thanks for reporting the issue
