### ISSUE TITLE
running the go examples returns deps error

### ISSUE THREAD

**Issue by tcrst** [multiversx/mx-sdk-go#28]
Running the go examples returns deps error

```
go mod tidy
go: finding module for package github.com/ElrondNetwork/elrond-sdk-erdgo/examples
go: finding module for package github.com/ElrondNetwork/elrond-sdk-erdgo/data
go: finding module for package github.com/ElrondNetwork/elrond-sdk-erdgo/blockchain
go: found github.com/ElrondNetwork/elrond-sdk-erdgo/blockchain in github.com/ElrondNetwork/elrond-sdk-erdgo v1.0.7
go: found github.com/ElrondNetwork/elrond-sdk-erdgo/data in github.com/ElrondNetwork/elrond-sdk-erdgo v1.0.7
go: found github.com/ElrondNetwork/elrond-sdk-erdgo/examples in github.com/ElrondNetwork/elrond-sdk-erdgo v1.0.7
go: github.com/ElrondNetwork/elrond-sdk-erdgo@v1.0.7 requires
	github.com/ElrondNetwork/elrond-go@v1.2.29 requires
	github.com/ElrondNetwork/arwen-wasm-vm/v1_2@v1.2.30: reading github.com/ElrondNetwork/arwen-wasm-vm/v1_2/v1_2/go.mod at revision v1_2/v1.2.30: unknown revision v1_2/v1.2.30
```

**Comment by ntminh611** [comment]
paste below code to go.mod
`module ElrondSwap

go 1.17

require (
	github.com/ElrondNetwork/elrond-go-logger v1.0.5
	github.com/ElrondNetwork/elrond-sdk-erdgo v1.0.7
)

require (
	github.com/ElrondNetwork/elrond-go-core v1.1.2 // indirect
	github.com/ElrondNetwork/elrond-go-crypto v1.0.1 // indirect
	github.com/btcsuite/btcutil v1.0.3-0.20201208143702-a53e38424cce // indirect
	github.com/denisbrodbeck/machineid v1.0.1 // indirect
	github.com/gogo/protobuf v1.3.2 // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/google/uuid v1.3.0 // indirect
	github.com/mr-tron/base58 v1.2.0 // indirect
	github.com/pborman/uuid v1.2.1 // indirect
	github.com/pelletier/go-toml v1.9.3 // indirect
	github.com/tyler-smith/go-bip39 v1.1.0 // indirect
	golang.org/x/crypto v0.0.0-20210711020723-a769d52b0f97 // indirect
	golang.org/x/sys v0.0.0-20210615035016-665e8c7367d1 // indirect
	google.golang.org/protobuf v1.26.0 // indirect
)

replace github.com/ElrondNetwork/arwen-wasm-vm/v1_2 v1.2.30 => github.com/ElrondNetwork/arwen-wasm-vm v1.2.30

replace github.com/ElrondNetwork/arwen-wasm-vm/v1_3 v1.3.30 => github.com/ElrondNetwork/arwen-wasm-vm v1.3.30

replace github.com/ElrondNetwork/arwen-wasm-vm/v1_4 v1.4.22 => github.com/ElrondNetwork/arwen-wasm-vm v1.4.22
`

**Comment by schimih** [comment]
This issue has been inactive for some time and a solution has already been suggested. If the problem still persists, we kindly ask that you open a new issue or join our Discord channel for further assistance.
https://discord.gg/multiversxbuilders
